metadata.format.version = "1.1"

[versions]
minecraft = "1.19.4"
parchment = "2023.03.12"

fabric-loom = "1.1-SNAPSHOT"
fabric-api = "0.76.0+1.19.4"
fabric-loader = "0.14.18"

mixinextras = "0.2.0-beta.6"

spotless = "6.17.0"
[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

mixinextras = { group = "com.github.LlamaLad7.MixinExtras", name = "mixinextras-fabric", version.ref = "mixinextras" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
